import React from 'react'; import {createRoot} from 'react-dom/client'; import {LoongArkProvider as Provider} from '@loongark/react'; import {ActionMediaExample as E0} from '../../../examples/react/ActionMediaExample.tsx';
import {AvatarExample as E1} from '../../../examples/react/AvatarExample.tsx';
import {CarouselExample as E2} from '../../../examples/react/CarouselExample.tsx';
import {CheckboxExample as E3} from '../../../examples/react/CheckboxExample.tsx';
import {ClipboardExample as E4} from '../../../examples/react/ClipboardExample.tsx';
import {ColorPickerExample as E5} from '../../../examples/react/ColorPickerExample.tsx';
import {ComboboxExample as E6} from '../../../examples/react/ComboboxExample.tsx';
import {EditableExample as E7} from '../../../examples/react/EditableExample.tsx';
import {FileUploadExample as E8} from '../../../examples/react/FileUploadExample.tsx';
import {FoundationsExample as E9} from '../../../examples/react/FoundationsExample.tsx';
import {HoverCardExample as E10} from '../../../examples/react/HoverCardExample.tsx';
import {ListboxExample as E11} from '../../../examples/react/ListboxExample.tsx';
import {NumberInputExample as E12} from '../../../examples/react/NumberInputExample.tsx';
import {PaginationExample as E13} from '../../../examples/react/PaginationExample.tsx';
import {PasswordInputExample as E14} from '../../../examples/react/PasswordInputExample.tsx';
import {ProgressExample as E15} from '../../../examples/react/ProgressExample.tsx';
import {RadioGroupExample as E16} from '../../../examples/react/RadioGroupExample.tsx';
import {RatingGroupExample as E17} from '../../../examples/react/RatingGroupExample.tsx';
import {ScrollAreaExample as E18} from '../../../examples/react/ScrollAreaExample.tsx';
import {SegmentGroupExample as E19} from '../../../examples/react/SegmentGroupExample.tsx';
import {SelectExample as E20} from '../../../examples/react/SelectExample.tsx';
import {SelectionInputsExample as E21} from '../../../examples/react/SelectionInputsExample.tsx';
import {SplitterExample as E22} from '../../../examples/react/SplitterExample.tsx';
import {StepsExample as E23} from '../../../examples/react/StepsExample.tsx';
import {SwitchExample as E24} from '../../../examples/react/SwitchExample.tsx';
import {TagsInputExample as E25} from '../../../examples/react/TagsInputExample.tsx';
import {ToastExample as E26} from '../../../examples/react/ToastExample.tsx';
import {TreeViewExample as E27} from '../../../examples/react/TreeViewExample.tsx'; const examples={'ActionMediaExample':E0,'AvatarExample':E1,'CarouselExample':E2,'CheckboxExample':E3,'ClipboardExample':E4,'ColorPickerExample':E5,'ComboboxExample':E6,'EditableExample':E7,'FileUploadExample':E8,'FoundationsExample':E9,'HoverCardExample':E10,'ListboxExample':E11,'NumberInputExample':E12,'PaginationExample':E13,'PasswordInputExample':E14,'ProgressExample':E15,'RadioGroupExample':E16,'RatingGroupExample':E17,'ScrollAreaExample':E18,'SegmentGroupExample':E19,'SelectExample':E20,'SelectionInputsExample':E21,'SplitterExample':E22,'StepsExample':E23,'SwitchExample':E24,'TagsInputExample':E25,'ToastExample':E26,'TreeViewExample':E27}; const name=new URLSearchParams(location.search).get('example') || 'ActionMediaExample'; const Selected=examples[name]; createRoot(document.getElementById('app')).render(<Provider><section style={{padding:24,minHeight:'100dvh',background:'var(--lk-color-semantic-background)',color:'var(--lk-color-semantic-foreground)'}}><h1 data-example-name>{name}</h1><div data-example-content><Selected/></div></section></Provider>);