<script>import {LoongArkProvider as Provider} from '@loongark/svelte'; import E0 from '../../../examples/svelte/ActionMediaExample.svelte';
import E1 from '../../../examples/svelte/AvatarExample.svelte';
import E2 from '../../../examples/svelte/CarouselExample.svelte';
import E3 from '../../../examples/svelte/ChartExample.svelte';
import E4 from '../../../examples/svelte/ClipboardExample.svelte';
import E5 from '../../../examples/svelte/ColorPickerExample.svelte';
import E6 from '../../../examples/svelte/ComboboxExample.svelte';
import E7 from '../../../examples/svelte/ConversationExample.svelte';
import E8 from '../../../examples/svelte/DataTableExample.svelte';
import E9 from '../../../examples/svelte/EditableExample.svelte';
import E10 from '../../../examples/svelte/FileUploadExample.svelte';
import E11 from '../../../examples/svelte/FoundationsExample.svelte';
import E12 from '../../../examples/svelte/HoverCardExample.svelte';
import E13 from '../../../examples/svelte/ListboxExample.svelte';
import E14 from '../../../examples/svelte/NumberInputExample.svelte';
import E15 from '../../../examples/svelte/PaginationExample.svelte';
import E16 from '../../../examples/svelte/PasswordInputExample.svelte';
import E17 from '../../../examples/svelte/ProgressExample.svelte';
import E18 from '../../../examples/svelte/RatingGroupExample.svelte';
import E19 from '../../../examples/svelte/ScrollAreaExample.svelte';
import E20 from '../../../examples/svelte/SegmentGroupExample.svelte';
import E21 from '../../../examples/svelte/SelectionInputsExample.svelte';
import E22 from '../../../examples/svelte/SplitterExample.svelte';
import E23 from '../../../examples/svelte/StepsExample.svelte';
import E24 from '../../../examples/svelte/SwitchExample.svelte';
import E25 from '../../../examples/svelte/TagsInputExample.svelte';
import E26 from '../../../examples/svelte/ToastExample.svelte';
import E27 from '../../../examples/svelte/TreeViewExample.svelte'; const examples={'ActionMediaExample':E0,'AvatarExample':E1,'CarouselExample':E2,'ChartExample':E3,'ClipboardExample':E4,'ColorPickerExample':E5,'ComboboxExample':E6,'ConversationExample':E7,'DataTableExample':E8,'EditableExample':E9,'FileUploadExample':E10,'FoundationsExample':E11,'HoverCardExample':E12,'ListboxExample':E13,'NumberInputExample':E14,'PaginationExample':E15,'PasswordInputExample':E16,'ProgressExample':E17,'RatingGroupExample':E18,'ScrollAreaExample':E19,'SegmentGroupExample':E20,'SelectionInputsExample':E21,'SplitterExample':E22,'StepsExample':E23,'SwitchExample':E24,'TagsInputExample':E25,'ToastExample':E26,'TreeViewExample':E27}; const name=new URLSearchParams(location.search).get('example') || 'ActionMediaExample'; const Selected=examples[name];</script><Provider><section style="padding:24px;min-height:100dvh;background:var(--lk-color-semantic-background);color:var(--lk-color-semantic-foreground)"><h1 data-example-name>{name}</h1><div data-example-content><Selected/></div></section></Provider>