import {test,expect} from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
for(const framework of ["react","vue","solid","svelte"])for(const mode of ["light","dark"])for(const width of [1280,375])
 test(`async collection ${framework} ${mode} ${width}`,async({page})=>{
  test.skip(!process.env.STATIC_DIR,"四端消费构建后运行");const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));await page.setViewportSize({width,height:1100});await page.goto(`/examples-${framework}/?example=AsyncCollectionExample&mode=${mode}`);
  const list=page.getByRole("list",{name:"Collection items"}),items=list.getByRole("listitem"),status=page.locator('p[role="status"]'),filter=page.getByRole("textbox",{name:"Filter collection",exact:true}),more=page.getByRole("button",{name:"Load more",exact:true});
  const ids=()=>items.evaluateAll(nodes=>nodes.map(n=>n.getAttribute("data-item-id")));
  await expect(page.getByLabel("Collection requests")).toHaveText("0 requests · 0 aborted");await expect(more).toBeDisabled();await page.getByRole("button",{name:"Load collection",exact:true}).click();await expect(status).toHaveText("Loading collection…");await expect(more).toBeDisabled();await expect(items).toHaveCount(3);await expect(more).toBeEnabled();expect(await ids()).toEqual(["item-1","item-2","item-3"]);
  await page.getByRole("button",{name:"Fail next request",exact:true}).click();await more.click();await expect(page.getByRole("alert")).toContainText("Demo service unavailable");await expect(more).toBeDisabled();await expect(items).toHaveCount(3);
  const errorSpacing = await page.getByRole("alert").evaluate(node => {
    const walker = document.createTreeWalker(node, NodeFilter.SHOW_TEXT);
    let label = walker.nextNode();while (label && !label.textContent?.trim()) label = walker.nextNode();
    const range = document.createRange();range.selectNodeContents(label!);
    const text = range.getBoundingClientRect(), retry = node.querySelector("button")!.getBoundingClientRect();
    return { gap: Math.max(retry.left - text.right, retry.top - text.bottom), textWidth: text.width };
  });
  expect(errorSpacing.textWidth).toBeGreaterThan(0);
  expect(errorSpacing.gap, "错误文字与重试按钮应有明确留白，包括手机换行").toBeGreaterThanOrEqual(7);
  await page.getByRole("button",{name:"Retry request",exact:true}).click();await expect(items).toHaveCount(5);expect(await ids()).toEqual(["item-1","item-2","item-3","item-4","item-5"]);await expect(page.getByRole("alert")).toHaveCount(0);await more.click();await expect(items).toHaveCount(6);await expect(more).toBeDisabled();
  await page.getByRole("button",{name:"Load collection",exact:true}).click();await expect(items).toHaveCount(3);await page.getByRole("button",{name:"Cycle next cursor",exact:true}).click();await more.click();await expect(page.getByRole("alert")).toContainText("cursor cycle");await expect(more).toBeDisabled();await expect(items).toHaveCount(3);
  expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);await page.screenshot({path:`.artifacts/advanced-completion/collection-error-${framework}-${mode}-${width}.png`,fullPage:true});await page.getByRole("button",{name:"Retry request",exact:true}).click();await expect(items).toHaveCount(5);
  await filter.fill("slow");await expect(status).toHaveText("Loading collection…");await filter.fill("fast");await expect(status).toHaveText("3 items · More pages available");expect(await ids()).toEqual(["fast-1","fast-2","fast-3"]);await expect(filter).toBeFocused();await page.waitForTimeout(700);expect(await ids()).toEqual(["fast-1","fast-2","fast-3"]);
  await more.click();await expect(items).toHaveCount(5);await page.getByRole("button",{name:"Sort descending",exact:true}).click();await expect(items).toHaveCount(3);expect(await ids()).toEqual(["fast-6","fast-5","fast-4"]);await more.click();await expect(items).toHaveCount(5);expect(await ids()).toEqual(["fast-6","fast-5","fast-4","fast-3","fast-2"]);await page.getByRole("button",{name:"Sort ascending",exact:true}).click();await expect(items).toHaveCount(3);expect(await ids()).toEqual(["fast-1","fast-2","fast-3"]);
  await filter.fill("slow");await expect(status).toHaveText("Loading collection…");await page.getByRole("button",{name:"Cancel request",exact:true}).click();await expect(status).not.toHaveText("Loading collection…");await expect(more).toBeDisabled();await page.waitForTimeout(700);expect(await ids()).toEqual(["fast-1","fast-2","fast-3"]);
  await filter.fill("new");await expect(items).toHaveCount(3);await expect(items.first()).toHaveAttribute("data-item-id","new-1");await more.click();await expect(items).toHaveCount(5);
  expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);await page.screenshot({path:`.artifacts/advanced-completion/collection-loaded-${framework}-${mode}-${width}.png`,fullPage:true});
  await filter.fill("slow");await expect(status).toHaveText("Loading collection…");await page.getByRole("button",{name:"Hide collection",exact:true}).click();await expect(list).toHaveCount(0);await expect(page.getByLabel("Disposed collections")).toHaveText("1 disposed");await page.waitForTimeout(700);await page.getByRole("button",{name:"Show collection",exact:true}).click();await expect(page.getByLabel("Collection requests")).toHaveText("0 requests · 0 aborted");await expect(items).toHaveCount(0);await page.getByRole("button",{name:"Load collection",exact:true}).click();await expect(items).toHaveCount(3);
  // 首次/重载失败必须重载，不能误用仍保留的旧分页游标。
  await page.getByRole("button",{name:"Fail next request",exact:true}).click();await page.getByRole("button",{name:"Load collection",exact:true}).click();await expect(page.getByRole("alert")).toContainText("Demo service unavailable");await expect(more).toBeDisabled();await expect(items).toHaveCount(0);await page.getByRole("button",{name:"Retry request",exact:true}).click();await expect(items).toHaveCount(3);expect(await ids()).toEqual(["item-1","item-2","item-3"]);
  expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 });

test("React StrictMode async loader survives effect replay",async({page})=>{test.skip(!process.env.STATIC_DIR,"消费构建后运行");const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));await page.goto("/examples-react/?example=AsyncCollectionExample&strict=true");await page.getByRole("button",{name:"Load collection",exact:true}).click();await expect(page.getByRole("list",{name:"Collection items"}).getByRole("listitem")).toHaveCount(3);await page.getByRole("button",{name:"Hide collection",exact:true}).click();await expect(page.getByLabel("Disposed collections")).toHaveText("1 disposed");await page.getByRole("button",{name:"Show collection",exact:true}).click();await page.getByRole("button",{name:"Load collection",exact:true}).click();await expect(page.getByRole("listitem")).toHaveCount(3);expect(errors).toEqual([]);});
