import {createApp,h} from 'vue'; import {LoongArkProvider as Provider} from '@loongark/vue'; import {ActionMediaExample as E0} from '../../../examples/vue/ActionMediaExample.ts';
import {AvatarExample as E1} from '../../../examples/vue/AvatarExample.ts';
import {CarouselExample as E2} from '../../../examples/vue/CarouselExample.ts';
import {ClipboardExample as E3} from '../../../examples/vue/ClipboardExample.ts';
import {ColorPickerExample as E4} from '../../../examples/vue/ColorPickerExample.ts';
import {ComboboxExample as E5} from '../../../examples/vue/ComboboxExample.ts';
import {ConversationExample as E6} from '../../../examples/vue/ConversationExample.ts';
import {EditableExample as E7} from '../../../examples/vue/EditableExample.ts';
import {FileUploadExample as E8} from '../../../examples/vue/FileUploadExample.ts';
import {FoundationsExample as E9} from '../../../examples/vue/FoundationsExample.ts';
import {HoverCardExample as E10} from '../../../examples/vue/HoverCardExample.ts';
import {ListboxExample as E11} from '../../../examples/vue/ListboxExample.ts';
import {NumberInputExample as E12} from '../../../examples/vue/NumberInputExample.ts';
import {PaginationExample as E13} from '../../../examples/vue/PaginationExample.ts';
import {PasswordInputExample as E14} from '../../../examples/vue/PasswordInputExample.ts';
import {ProgressExample as E15} from '../../../examples/vue/ProgressExample.ts';
import {RatingGroupExample as E16} from '../../../examples/vue/RatingGroupExample.ts';
import {ScrollAreaExample as E17} from '../../../examples/vue/ScrollAreaExample.ts';
import {SegmentGroupExample as E18} from '../../../examples/vue/SegmentGroupExample.ts';
import {SelectionInputsExample as E19} from '../../../examples/vue/SelectionInputsExample.ts';
import {SplitterExample as E20} from '../../../examples/vue/SplitterExample.ts';
import {StepsExample as E21} from '../../../examples/vue/StepsExample.ts';
import {SwitchExample as E22} from '../../../examples/vue/SwitchExample.ts';
import {TagsInputExample as E23} from '../../../examples/vue/TagsInputExample.ts';
import {ToastExample as E24} from '../../../examples/vue/ToastExample.ts';
import {TreeViewExample as E25} from '../../../examples/vue/TreeViewExample.ts'; const examples={'ActionMediaExample':E0,'AvatarExample':E1,'CarouselExample':E2,'ClipboardExample':E3,'ColorPickerExample':E4,'ComboboxExample':E5,'ConversationExample':E6,'EditableExample':E7,'FileUploadExample':E8,'FoundationsExample':E9,'HoverCardExample':E10,'ListboxExample':E11,'NumberInputExample':E12,'PaginationExample':E13,'PasswordInputExample':E14,'ProgressExample':E15,'RatingGroupExample':E16,'ScrollAreaExample':E17,'SegmentGroupExample':E18,'SelectionInputsExample':E19,'SplitterExample':E20,'StepsExample':E21,'SwitchExample':E22,'TagsInputExample':E23,'ToastExample':E24,'TreeViewExample':E25}; const name=new URLSearchParams(location.search).get('example') || 'ActionMediaExample'; const Selected=examples[name]; createApp({render:()=>h(Provider,{},()=>h('section',{style:'padding:24px;min-height:100dvh'},[h('h1',{'data-example-name':''},name),h('div',{'data-example-content':''},[h(Selected)])]))}).mount('#app');