import {render} from 'solid-js/web'; import {LoongArkProvider as Provider} from '@loongark/solid'; import {ActionMediaExample as E0} from '../../../examples/solid/ActionMediaExample.tsx';
import {AvatarExample as E1} from '../../../examples/solid/AvatarExample.tsx';
import {CarouselExample as E2} from '../../../examples/solid/CarouselExample.tsx';
import {ClipboardExample as E3} from '../../../examples/solid/ClipboardExample.tsx';
import {ColorPickerExample as E4} from '../../../examples/solid/ColorPickerExample.tsx';
import {ComboboxExample as E5} from '../../../examples/solid/ComboboxExample.tsx';
import {ConversationExample as E6} from '../../../examples/solid/ConversationExample.tsx';
import {DataTableExample as E7} from '../../../examples/solid/DataTableExample.tsx';
import {EditableExample as E8} from '../../../examples/solid/EditableExample.tsx';
import {FileUploadExample as E9} from '../../../examples/solid/FileUploadExample.tsx';
import {FoundationsExample as E10} from '../../../examples/solid/FoundationsExample.tsx';
import {HoverCardExample as E11} from '../../../examples/solid/HoverCardExample.tsx';
import {ListboxExample as E12} from '../../../examples/solid/ListboxExample.tsx';
import {NumberInputExample as E13} from '../../../examples/solid/NumberInputExample.tsx';
import {PaginationExample as E14} from '../../../examples/solid/PaginationExample.tsx';
import {PasswordInputExample as E15} from '../../../examples/solid/PasswordInputExample.tsx';
import {ProgressExample as E16} from '../../../examples/solid/ProgressExample.tsx';
import {RatingGroupExample as E17} from '../../../examples/solid/RatingGroupExample.tsx';
import {ScrollAreaExample as E18} from '../../../examples/solid/ScrollAreaExample.tsx';
import {SegmentGroupExample as E19} from '../../../examples/solid/SegmentGroupExample.tsx';
import {SelectionInputsExample as E20} from '../../../examples/solid/SelectionInputsExample.tsx';
import {SplitterExample as E21} from '../../../examples/solid/SplitterExample.tsx';
import {StepsExample as E22} from '../../../examples/solid/StepsExample.tsx';
import {SwitchExample as E23} from '../../../examples/solid/SwitchExample.tsx';
import {TagsInputExample as E24} from '../../../examples/solid/TagsInputExample.tsx';
import {ToastExample as E25} from '../../../examples/solid/ToastExample.tsx';
import {TreeViewExample as E26} from '../../../examples/solid/TreeViewExample.tsx'; const examples={'ActionMediaExample':E0,'AvatarExample':E1,'CarouselExample':E2,'ClipboardExample':E3,'ColorPickerExample':E4,'ComboboxExample':E5,'ConversationExample':E6,'DataTableExample':E7,'EditableExample':E8,'FileUploadExample':E9,'FoundationsExample':E10,'HoverCardExample':E11,'ListboxExample':E12,'NumberInputExample':E13,'PaginationExample':E14,'PasswordInputExample':E15,'ProgressExample':E16,'RatingGroupExample':E17,'ScrollAreaExample':E18,'SegmentGroupExample':E19,'SelectionInputsExample':E20,'SplitterExample':E21,'StepsExample':E22,'SwitchExample':E23,'TagsInputExample':E24,'ToastExample':E25,'TreeViewExample':E26}; const name=new URLSearchParams(location.search).get('example') || 'ActionMediaExample'; const Selected=examples[name]; render(()=><Provider><section style="padding:24px;min-height:100dvh;background:var(--lk-color-semantic-background);color:var(--lk-color-semantic-foreground)"><h1 data-example-name>{name}</h1><div data-example-content><Selected/></div></section></Provider>,document.getElementById('app'));