import {render} from 'solid-js/web'; import {LoongArkProvider as Provider} from '@loongark/solid'; import {ActionMediaExample as E0} from '../../../examples/solid/ActionMediaExample.tsx';
import {AvatarExample as E1} from '../../../examples/solid/AvatarExample.tsx';
import {CarouselExample as E2} from '../../../examples/solid/CarouselExample.tsx';
import {ChartExample as E3} from '../../../examples/solid/ChartExample.tsx';
import {ClipboardExample as E4} from '../../../examples/solid/ClipboardExample.tsx';
import {ColorPickerExample as E5} from '../../../examples/solid/ColorPickerExample.tsx';
import {ComboboxExample as E6} from '../../../examples/solid/ComboboxExample.tsx';
import {ConversationExample as E7} from '../../../examples/solid/ConversationExample.tsx';
import {DataTableExample as E8} from '../../../examples/solid/DataTableExample.tsx';
import {EditableExample as E9} from '../../../examples/solid/EditableExample.tsx';
import {FileUploadExample as E10} from '../../../examples/solid/FileUploadExample.tsx';
import {FoundationsExample as E11} from '../../../examples/solid/FoundationsExample.tsx';
import {HoverCardExample as E12} from '../../../examples/solid/HoverCardExample.tsx';
import {ListboxExample as E13} from '../../../examples/solid/ListboxExample.tsx';
import {NumberInputExample as E14} from '../../../examples/solid/NumberInputExample.tsx';
import {PaginationExample as E15} from '../../../examples/solid/PaginationExample.tsx';
import {PasswordInputExample as E16} from '../../../examples/solid/PasswordInputExample.tsx';
import {ProgressExample as E17} from '../../../examples/solid/ProgressExample.tsx';
import {RatingGroupExample as E18} from '../../../examples/solid/RatingGroupExample.tsx';
import {ScrollAreaExample as E19} from '../../../examples/solid/ScrollAreaExample.tsx';
import {SegmentGroupExample as E20} from '../../../examples/solid/SegmentGroupExample.tsx';
import {SelectionInputsExample as E21} from '../../../examples/solid/SelectionInputsExample.tsx';
import {SplitterExample as E22} from '../../../examples/solid/SplitterExample.tsx';
import {StepsExample as E23} from '../../../examples/solid/StepsExample.tsx';
import {SwitchExample as E24} from '../../../examples/solid/SwitchExample.tsx';
import {TagsInputExample as E25} from '../../../examples/solid/TagsInputExample.tsx';
import {ToastExample as E26} from '../../../examples/solid/ToastExample.tsx';
import {TreeViewExample as E27} from '../../../examples/solid/TreeViewExample.tsx'; const examples={'ActionMediaExample':E0,'AvatarExample':E1,'CarouselExample':E2,'ChartExample':E3,'ClipboardExample':E4,'ColorPickerExample':E5,'ComboboxExample':E6,'ConversationExample':E7,'DataTableExample':E8,'EditableExample':E9,'FileUploadExample':E10,'FoundationsExample':E11,'HoverCardExample':E12,'ListboxExample':E13,'NumberInputExample':E14,'PaginationExample':E15,'PasswordInputExample':E16,'ProgressExample':E17,'RatingGroupExample':E18,'ScrollAreaExample':E19,'SegmentGroupExample':E20,'SelectionInputsExample':E21,'SplitterExample':E22,'StepsExample':E23,'SwitchExample':E24,'TagsInputExample':E25,'ToastExample':E26,'TreeViewExample':E27}; const name=new URLSearchParams(location.search).get('example') || 'ActionMediaExample'; const Selected=examples[name]; render(()=><Provider><section style="padding:24px;min-height:100dvh;background:var(--lk-color-semantic-background);color:var(--lk-color-semantic-foreground)"><h1 data-example-name>{name}</h1><div data-example-content><Selected/></div></section></Provider>,document.getElementById('app'));